name: Perks-Extras
main: co.neweden.perks.extras.Main
author: AaronMcH
description: Useful perks
website: https://neweden.co/
version: 1.0-RELEASE
softdepend: [PermissionsEx]
commands:
  bitchslap:
    description: Bitch Slap a player
    permission: perks.extras.bitchslap
  brofist:
    description: Fist Bump a player
    permission: perks.extras.brofist
  highfive:
    description: HIgh Five a player
    permission: perks.extras.highfive
  pickup:
    description: Pickup items around you in a radius
    permission: perks.extras.pickup
  prefix:
    description: Change your chat prefix
    permissions: perks.extras.prefix
  pweather:
    description: Change the current weather for you or another player
    permissions: perks.extras.pweather
  rainbowsheep:
    description: Spawn one of every colour hseep around a player
    permission: perks.extras.rainbowsheep
  slap:
    description: Slap a player
    permission: perks.extras.slap
permissions:
  perks.extras.*:
    description: Gives all Perks Extras permissions
    default: op
    children:
      perks.extras.bitchslap: true
      perks.extras.bitchslap.bypass.cooldown: true
      perks.extras.brofist: true
      perks.extras.highfive: true
      perks.extras.pickup: true
      perks.extras.pickup.bypass.cooldown: true
      perks.extras.pickup.bypass.radius: true
      perks.extras.prefix: true
      perks.extras.pweather: true
      perks.extras.rainbowsheep: true
      perks.extras.slap: true
      perks.extras.slap.bypass.cooldown: true
      perks.extras.canttouchthis: true
  perks.extras.bitchslap.bypass.cooldown:
    description: Bypass cooldown
  perks.extras.canttouchthis:
    description: Prevents a given player from being slapped or bitch slapped
  perks.extras.pweather.others:
    description: Change the player specific weather for other players
  perks.extras.pickup.bypass.cooldown:
    description: Bypass cooldown
  perks.extras.pickup.bypass.radius:
    description: Bypass radius limitations
  perks.extras.slap.bypass.cooldown:
    description: Bypass cooldown
