name: Perks
main: co.neweden.Perks.Main
author: AaronMcH
description: Perks plugin for New Eden
website: https://neweden.co/
version: 0.1
depend: [MenuGUI]
commands:
   perks:
      description: Commands to display perks
      permission: perks.perks