name: Perks
main: co.neweden.Perks.Main
author: AaronMcH
description: Perks plugin for New Eden
website: https://neweden.co/
version: 1.0-RELEASE
depend: [MenuGUI]
commands:
   perks:
      description: Commands to display perks
      permission: perks.perks
permissions:
   perks.*:
      description: Gives all Perks permission nodes
      default: op
      children:
         perks.perks: true
         perks.admin: true
   perks.perks:
      description: User command to see and buy perks
   perks.admin:
      description: Gives access to view help pages and administer perks
